version: '3'
services:
  web:
    volumes:
      - /home/liamirpy/Downloads/1:/appp
      - ./app:/app
    ports:
      - "100:100"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=100'
    command: flask run --host=0.0.0.0 --port=100
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
